
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bie
 */
public class LoginForm extends javax.swing.JFrame {
String status;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    //    this.setLocationRelativeTo(null); // center form screen
        
 //       setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH); //fullscreen
     
/*                Toolkit tk = Toolkit.getDefaultToolkit(); //full screen
        int xsize=(int) tk.getScreenSize().getWidth();
         int ysize=(int) tk.getScreenSize().getHeight();
         this.setSize(xsize,ysize); */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        UserBox = new javax.swing.JTextField();
        PassBox = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelMin = new javax.swing.JLabel();
        LabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 40, 50));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Phetsarath OT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ຊື່ຜູ້ໃຊ້");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 320, 80, 36);

        UserBox.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        UserBox.setToolTipText("");
        UserBox.setFocusCycleRoot(true);
        UserBox.setName(""); // NOI18N
        UserBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserBoxActionPerformed(evt);
            }
        });
        UserBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserBoxKeyPressed(evt);
            }
        });
        jPanel2.add(UserBox);
        UserBox.setBounds(70, 360, 320, 40);

        PassBox.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        PassBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassBoxKeyPressed(evt);
            }
        });
        jPanel2.add(PassBox);
        PassBox.setBounds(70, 450, 320, 40);

        btnLogin.setBackground(new java.awt.Color(0, 204, 204));
        btnLogin.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("ເຂົ້າສູ່ລະບົບ");
        btnLogin.setToolTipText("");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(100, 530, 250, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bie\\Downloads\\user (3).png")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 180, 128, 128);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Phetsarath OT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("ລະຫັດຜ່ານ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 420, 97, 36);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Library ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(150, 0, 200, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Management System");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 60, 390, 90);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 65, 446, 640));

        LabelMin.setBackground(new java.awt.Color(0, 0, 153));
        LabelMin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LabelMin.setForeground(new java.awt.Color(255, 255, 255));
        LabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMin.setText("-");
        LabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelMinMouseClicked(evt);
            }
        });
        getContentPane().add(LabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 40, -1));

        LabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/books.jpg"))); // NOI18N
        LabelBackground.setName(""); // NOI18N
        LabelBackground.setNextFocusableComponent(jLabel4);
        getContentPane().add(LabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
          
         String uname = UserBox.getText();
    String pass = String.valueOf(PassBox.getPassword());
           
    
    String query = "SELECT * FROM tb_employee WHERE uname =? AND pass =?";
        try {
            ps= MyConnection.getConnection().prepareStatement(query);
           
            ps.setString(1, uname);
            ps.setString(2, pass);
           
            rs = ps.executeQuery();
          
            if(rs.next()){
              Home h = new Home();
          status= rs.getString("Status");
              if(status.equalsIgnoreCase("Admin" )||status.equalsIgnoreCase("admin" )){
                  
              
                    
                h.setVisible(true);
//                h.pack();
//                h.setLocationRelativeTo(null);
//                h.setExtendedState(JFrame.MAXIMIZED_BOTH);
               
                this.dispose();  
              }
              if(status.equalsIgnoreCase("User" )||status.equalsIgnoreCase("user" )){
             
             //   h.setBtnDisable();
             h.disablemenu();
                h.setVisible(true);
//                h.pack();
//                h.setLocationRelativeTo(null);
//                h.setExtendedState(JFrame.MAXIMIZED_BOTH);
               
                this.dispose(); }
               
                
            }else{
                JOptionPane.showMessageDialog(null, "Username or Password not correct !!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        UserBox.setText("");
        PassBox.setText("");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void UserBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserBoxActionPerformed

    private void UserBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserBoxKeyPressed
     if(evt.getKeyCode () == KeyEvent.VK_ENTER){
         PassBox.requestFocus();
     }
    }//GEN-LAST:event_UserBoxKeyPressed

    private void PassBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassBoxKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         
           
                PreparedStatement ps;
        ResultSet rs;
          
         String uname = UserBox.getText();
    String pass = String.valueOf(PassBox.getPassword());
           
    
    String query = "SELECT * FROM tb_employee WHERE uname =? AND pass =?";
        try {
            ps= MyConnection.getConnection().prepareStatement(query);
           
            ps.setString(1, uname);
            ps.setString(2, pass);
           
            rs = ps.executeQuery();
          
            if(rs.next()){
              Home h = new Home();
           status= rs.getString("Status");
              if(status.equalsIgnoreCase("Admin" )||status.equalsIgnoreCase("admin" )){
                  
              //br dai
                    
                h.setVisible(true);
                h.pack();
                h.setLocationRelativeTo(null);
                h.setExtendedState(JFrame.MAXIMIZED_BOTH);
               
                this.dispose();  
              }
              if(status.equalsIgnoreCase("User" )||status.equalsIgnoreCase("user" )){
       
          h.disablemenu();
                h.setVisible(true);
                h.pack();
                h.setLocationRelativeTo(null);
                h.setExtendedState(JFrame.MAXIMIZED_BOTH);
               
                this.dispose(); }
               
                
            }else{
                JOptionPane.showMessageDialog(null, "Username or Password not correct !!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_PassBoxKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   
    }//GEN-LAST:event_formWindowOpened

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
     System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void LabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_LabelMinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBackground;
    private javax.swing.JLabel LabelMin;
    private javax.swing.JPasswordField PassBox;
    private javax.swing.JTextField UserBox;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
