
import com.sun.xml.internal.ws.util.StringUtils;


import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bie
 */
public class MemberForm extends javax.swing.JFrame {
  Connection c = MyConnection.getConnection();
    PreparedStatement ps;
    ResultSet rs;
     DefaultTableModel model = new DefaultTableModel();
     
     String filename;
     byte[] photo;
    /**
     * Creates new form RegisterForm
     */
    public MemberForm() {
        initComponents();
         this.setLocationRelativeTo(null); // center form screen
               setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    /*    Toolkit tk = Toolkit.getDefaultToolkit(); // full screen
        int xsize=(int) tk.getScreenSize().getWidth();
         int ysize=(int) tk.getScreenSize().getHeight();
         this.setSize(xsize,ysize); */
    
     model = (DefaultTableModel) tbModel.getModel();
        showData();
    
    BirthdateBox.setDate(new Date());
    }
    
    
     private void showData() {
      int row = tbModel.getRowCount()-1;
      while(row>=0)
      {
          model.removeRow(row--);
      }
        try {
               String select  =  "select * from tb_member";
      ResultSet rs = c.createStatement().executeQuery(select);
      while(rs.next())
      {
         String []  arr = {String.valueOf(rs.getInt("m_id")),String.valueOf(rs.getString("m_name")),
         String.valueOf(rs.getString("m_lastname")),String.valueOf(rs.getInt("m_age")),
                        String.valueOf(rs.getString("m_gender")),
                         String.valueOf(rs.getDate("m_birthdate")),String.valueOf(rs.getString("m_village")),
                         String.valueOf(rs.getString("m_city")),String.valueOf(rs.getString("m_province")),
                         String.valueOf(rs.getInt("m_phonenumber")),String.valueOf(rs.getBytes("m_picture"))};
         model.addRow(arr);
      }
      
        } catch (Exception e) {
            e.printStackTrace();
        }
   
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        LastnameBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        FirstnameBox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BirthdateBox = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        phonenumberbox = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        provinceBox = new javax.swing.JTextField();
        villageBox = new javax.swing.JTextField();
        cityBox = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbModel = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        labelPhoto = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        idBox = new javax.swing.JTextField();
        btnChoose = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/house.png"))); // NOI18N
        jButton2.setText("ໜ້າຫຼັກ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setBackground(new java.awt.Color(0, 255, 0));
        btnSave.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add5.gif"))); // NOI18N
        btnSave.setText("ເພິ່ມ");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnSaveKeyTyped(evt);
            }
        });
        jPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 120, 59));

        btnEdit.setBackground(new java.awt.Color(255, 0, 0));
        btnEdit.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit5.gif"))); // NOI18N
        btnEdit.setText("ແກ້ໄຂ");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 120, 59));

        jLabel10.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ນາມສະກຸນ :");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        LastnameBox.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        LastnameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameBoxActionPerformed(evt);
            }
        });
        LastnameBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LastnameBoxKeyPressed(evt);
            }
        });
        jPanel4.add(LastnameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 170, 29));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ຮູບ:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        FirstnameBox.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        FirstnameBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FirstnameBoxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FirstnameBoxKeyReleased(evt);
            }
        });
        jPanel4.add(FirstnameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 170, 29));

        jLabel13.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ວັນເດືອນປີເກີດ :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));
        jPanel4.add(BirthdateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 170, 31));

        jLabel14.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ເພດ :");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        buttonGroup1.add(rbmale);
        rbmale.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        rbmale.setForeground(new java.awt.Color(255, 255, 255));
        rbmale.setText("ຊາຍ");
        jPanel4.add(rbmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        buttonGroup1.add(rbfemale);
        rbfemale.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        rbfemale.setForeground(new java.awt.Color(255, 255, 255));
        rbfemale.setText("ຍິງ");
        jPanel4.add(rbfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        jLabel15.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ເບີໂທ :");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        phonenumberbox.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        phonenumberbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumberboxActionPerformed(evt);
            }
        });
        phonenumberbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenumberboxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonenumberboxKeyTyped(evt);
            }
        });
        jPanel4.add(phonenumberbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 170, 30));

        jLabel16.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ບ້ານ :");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel17.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ແຂວງ :");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        jLabel18.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ເມືອງ :");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        provinceBox.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        provinceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceBoxActionPerformed(evt);
            }
        });
        provinceBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                provinceBoxKeyPressed(evt);
            }
        });
        jPanel4.add(provinceBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 170, 29));

        villageBox.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        villageBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villageBoxActionPerformed(evt);
            }
        });
        villageBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                villageBoxKeyPressed(evt);
            }
        });
        jPanel4.add(villageBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 170, 29));

        cityBox.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        cityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityBoxActionPerformed(evt);
            }
        });
        cityBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityBoxKeyPressed(evt);
            }
        });
        jPanel4.add(cityBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 170, 29));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Phetsarath OT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("ຈັດການຂໍ້ມູນສະມາຊິກ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 0, 440, 70);

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 70));

        tbModel.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        tbModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "m_id", "m_name", "m_lastname", "m_age", "m_gender", "m_birthdate", "m_village", "m_city", "m_province", "m_phonenumber", "m_picture"
            }
        ));
        tbModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbModelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbModel);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 700, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ຊື່ :");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        labelPhoto.setForeground(new java.awt.Color(255, 255, 255));
        labelPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.add(labelPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 90, 100));

        btnDelete.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete5.gif"))); // NOI18N
        btnDelete.setText("ລົບ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 110, 60));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ລະຫັດ ສະມາຊິກ :");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        idBox.setEnabled(false);
        idBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idBoxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idBoxKeyReleased(evt);
            }
        });
        jPanel4.add(idBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 170, 29));

        btnChoose.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        btnChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/browsButton.png"))); // NOI18N
        btnChoose.setText("ເລືອກ");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });
        jPanel4.add(btnChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, 30));

        jButton1.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clearButton.png"))); // NOI18N
        jButton1.setText("ລ້າງ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 100, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 1210, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/books.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phonenumberboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenumberboxKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();

        }
    }//GEN-LAST:event_phonenumberboxKeyTyped

    private void phonenumberboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_phonenumberboxActionPerformed

    private void FirstnameBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstnameBoxKeyReleased
/*        int position = FirstnameBox.getCaretPosition();
        FirstnameBox.setText(FirstnameBox.getText().substring(0,1).toUpperCase()+FirstnameBox.getText().substring(1));
        FirstnameBox.setCaretPosition(position); */
    }//GEN-LAST:event_FirstnameBoxKeyReleased

    private void LastnameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameBoxActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      try {
            String sql="UPDATE `tb_member` SET `m_name`=?,`m_lastname`=?,m_age=?,`m_gender`=?,`m_birthdate`=?,`m_village`=?,`m_city`=?,`m_province`=?,`m_phonenumber`=?,`m_picture`=? WHERE `m_id`=?";
               String gender="";
               SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           
            String bdate = sdf.format(BirthdateBox.getDate());
             LocalDate today = LocalDate.now();
            LocalDate birthdate = LocalDate.parse(bdate);
               int age= Period.between(birthdate,today).getYears();
               
               int phone = Integer.valueOf(phonenumberbox.getText());
            ps = c.prepareStatement(sql);
 
             ps.setString(11, idBox.getText());
            ps.setString(1, FirstnameBox.getText());
            ps.setString(2, LastnameBox.getText());
     
            if(rbmale.isSelected()){
               gender= rbmale.getText();
            }else{
              gender=  rbfemale.getText();
            }
            ps.setInt(3, age);
            ps.setString(4, gender);
           
           
            
            ps.setString(5, sdf.format(BirthdateBox.getDate()));
            ps.setString(6, villageBox.getText());
            ps.setString(7,cityBox.getText());
            ps.setString(8, provinceBox.getText());
            ps.setInt(9,phone);
         
             //Set Picture for Edit////////////////////////////////////////////////////////////////////////////////////           

             ps.setBytes(10, photo);
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
           
            if(ps.executeUpdate()!=-1){
                    JOptionPane.showMessageDialog(null, "complete","save",JOptionPane.INFORMATION_MESSAGE);
                }
            
            
            showData();
          idBox.setText("");
                  BirthdateBox.setDate(new Date());
                    FirstnameBox.setText("");
        LastnameBox.setText("");
    
   phonenumberbox.setText("");

   
     
       villageBox.setText("");
     cityBox.setText("");
     provinceBox.setText("");
     
     labelPhoto.setIcon(new ImageIcon());
          
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Connection c=MyConnection.getConnection();

        String fname = FirstnameBox.getText();
        String lname = LastnameBox.getText();
        String phonenum = phonenumberbox.getText();
        String gender = "";

     
        String village = villageBox.getText();
        String city = cityBox.getText();
        String province = provinceBox.getText();

        if (rbmale.isSelected()) {
            gender=rbmale.getText();

        }
        if (rbfemale.isSelected()) {
            gender=rbfemale.getText();

        }

        if( fname.equals("") || lname.equals("") || phonenum.equals("") || gender.equals("") || village.equals("") || city.equals("") || province.equals("")){
            JOptionPane.showMessageDialog(null, "Please Fill All Information");
        }

        //   else if(BirthdateBox.getDate()!=null){
            //      SimpleDateFormat dataformat = new SimpleDateFormat("yyyy-mm-dd");
            //    bdate = dataformat.format(BirthdateBox.getDate());
            //  }
        else{
           
            SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
            String bdate = dateformat.format(BirthdateBox.getDate());
           
            LocalDate today = LocalDate.now();
            LocalDate birthdate = LocalDate.parse(bdate);
int age= Period.between(birthdate,today).getYears();
            // PreparedStatement ps;
            // String query = "insert into tbregister values(?,?,?,?,?)";
            try{
                //  ps = MyConnection.getConnection().prepareStatement(sql);
                String sql="INSERT INTO `tb_member`( `m_name`, `m_lastname`,m_age,`m_gender`, `m_birthdate`, `m_village`, `m_city`, `m_province`, `m_phonenumber`, `m_picture`) VALUES (?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement ps=c.prepareStatement(sql);
    
                ps.setString(1, fname);
                ps.setString(2, lname);
                ps.setInt(3, age);
   ps.setString(4, gender);
                if(bdate != null){
                    ps.setString(5, bdate); }
                 ps.setString(6, village);
                ps.setString(7, city);
                ps.setString(8, province);
                ps.setString(9, phonenum);
              
                ps.setBytes(10, photo);

              
                if(ps.executeUpdate()!=-1){
                    JOptionPane.showMessageDialog(null, "complete","save",JOptionPane.INFORMATION_MESSAGE);
                }
                showData();
                
                idBox.setText("");
                  BirthdateBox.setDate(new Date());
                    FirstnameBox.setText("");
        LastnameBox.setText("");  
   phonenumberbox.setText("");

       villageBox.setText("");
     cityBox.setText("");
     provinceBox.setText("");
     
     labelPhoto.setIcon(new ImageIcon());
            }catch (Exception e){
                // Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE,null,e);
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnSaveActionPerformed

  /*  public boolean checkusername(String uname){
    
                PreparedStatement ps;
                ResultSet rs;
                boolean checkuser =false;
                String sql ="select * from tbregis where uname=?";
                
                try {
            ps = MyConnection.getConnection().prepareStatement(sql);
            ps.setString(1, uname);
            rs = ps.executeQuery();
            
            if(rs.next()){
                checkuser=true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
                return checkuser;
    }
    */
    
    private void provinceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinceBoxActionPerformed

    private void villageBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villageBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_villageBoxActionPerformed

    private void cityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityBoxActionPerformed

    private void FirstnameBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstnameBoxKeyPressed
     if(evt.getKeyCode()==KeyEvent.VK_ENTER){
         LastnameBox.requestFocus();
     }
    }//GEN-LAST:event_FirstnameBoxKeyPressed

    private void LastnameBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastnameBoxKeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER){
     villageBox.requestFocus();
 }
    }//GEN-LAST:event_LastnameBoxKeyPressed

    private void villageBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_villageBoxKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        cityBox.requestFocus();
    }
    }//GEN-LAST:event_villageBoxKeyPressed

    private void cityBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityBoxKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          provinceBox.requestFocus();
      }
    }//GEN-LAST:event_cityBoxKeyPressed

    private void provinceBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_provinceBoxKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        phonenumberbox.requestFocus();
    }
    }//GEN-LAST:event_provinceBoxKeyPressed

    private void phonenumberboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenumberboxKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
         Connection c=MyConnection.getConnection();

        String fname = FirstnameBox.getText();
        String lname = LastnameBox.getText();
        String phonenum = phonenumberbox.getText();
        String gender = "";

     
        String village = villageBox.getText();
        String city = cityBox.getText();
        String province = provinceBox.getText();

        if (rbmale.isSelected()) {
            gender=rbmale.getText();

        }
        if (rbfemale.isSelected()) {
            gender=rbfemale.getText();

        }

        if( fname.equals("") || lname.equals("") || phonenum.equals("") || gender.equals("") || village.equals("") || city.equals("") || province.equals("")){
            JOptionPane.showMessageDialog(null, "Please Fill All Information");
        }

        //   else if(BirthdateBox.getDate()!=null){
            //      SimpleDateFormat dataformat = new SimpleDateFormat("yyyy-mm-dd");
            //    bdate = dataformat.format(BirthdateBox.getDate());
            //  }
        else{
           
            SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
            String bdate = dateformat.format(BirthdateBox.getDate());
           
            LocalDate today = LocalDate.now();
            LocalDate birthdate = LocalDate.parse(bdate);
int age= Period.between(birthdate,today).getYears();
            // PreparedStatement ps;
            // String query = "insert into tbregister values(?,?,?,?,?)";
            try{
                //  ps = MyConnection.getConnection().prepareStatement(sql);
                String sql="INSERT INTO `tb_member`( `m_name`, `m_lastname`,'m_age',`m_gender`, `m_birthdate`, `m_village`, `m_city`, `m_province`, `m_phonenumber`, `m_picture`) VALUES (?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement ps=c.prepareStatement(sql);
    
                ps.setString(1, fname);
                ps.setString(2, lname);
                ps.setInt(3, age);
   ps.setString(4, gender);
                if(bdate != null){
                    ps.setString(5, bdate); }
                 ps.setString(6, village);
                ps.setString(7, city);
                ps.setString(8, province);
                ps.setString(9, phonenum);
              
                ps.setString(10, null);

              
                if(ps.executeUpdate()!=-1){
                    JOptionPane.showMessageDialog(null, "complete","save",JOptionPane.INFORMATION_MESSAGE);
                }
                idBox.setText("");
                  BirthdateBox.setDate(new Date());
                    FirstnameBox.setText("");
        LastnameBox.setText("");
    
   phonenumberbox.setText("");
    rbfemale= new JRadioButton();
    rbmale= new JRadioButton();
   
     
       villageBox.setText("");
     cityBox.setText("");
     provinceBox.setText("");
     labelPhoto.setIcon(new ImageIcon());
            }catch (Exception e){
                // Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE,null,e);
                e.printStackTrace();
            }
        }
    }
    }//GEN-LAST:event_phonenumberboxKeyPressed

    private void btnSaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveKeyTyped

    private void idBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idBoxKeyPressed

    private void idBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idBoxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_idBoxKeyReleased

    
      public ImageIcon ResizeImage(String ImagePath, byte[] pic)
    {
        ImageIcon MyImage = null;
        if(ImagePath != null)
        {
           MyImage = new ImageIcon(ImagePath);
        }else
        {
            MyImage = new ImageIcon(pic);
        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(labelPhoto.getWidth(), labelPhoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void tbModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbModelMouseClicked
        try {
            int index = tbModel.getSelectedRow();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            idBox.setText(tbModel.getValueAt(index, 0).toString());
            FirstnameBox.setText((String) tbModel.getValueAt(index, 1));
            LastnameBox.setText(tbModel.getValueAt(index, 2).toString());
             String gender = tbModel.getValueAt(index, 4).toString();
            if(gender.equals("ຊາຍ")){
                rbmale.setSelected(true);
            }else{
                rbfemale.setSelected(true);
            }
         
            BirthdateBox.setDate(sdf.parse(tbModel.getValueAt(index, 5).toString()));
            villageBox.setText(tbModel.getValueAt(index, 6).toString());
            cityBox.setText(tbModel.getValueAt(index,7).toString());
            provinceBox.setText(tbModel.getValueAt(index, 8).toString());
            phonenumberbox.setText(tbModel.getValueAt(index,9).toString());
            
//           JLabel image = (JLabel) tbModel.getValueAt(index, 10);
  //         ImageIcon imageicon = (ImageIcon) image.getIcon();
  //         labelPhoto.setIcon(imageicon);

      
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
         try{
            int index = tbModel.getSelectedRow();
         String select = "select m_picture from tb_member where m_id=?";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(select);
            ps.setString(1,tbModel.getValueAt(index, 0).toString());
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                labelPhoto.setIcon(ResizeImage(null, rs.getBytes("m_picture")));
                photo = rs.getBytes("m_picture");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbModelMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    try {
        Connection c = MyConnection.getConnection();
            String sql="DELETE FROM `tb_member` where m_id=?";
            
       PreparedStatement  ps = c.prepareStatement(sql);
 
             ps.setString(1, idBox.getText());
         
       if(ps.executeUpdate()!=-1){
                    JOptionPane.showMessageDialog(null, "complete","save",JOptionPane.INFORMATION_MESSAGE);
                    
                      
                }
            showData();
           idBox.setText("");
            FirstnameBox.setText("");
          LastnameBox.setText("");

          BirthdateBox.setDate(new Date()); 
           villageBox.setText("");
           cityBox.setText("");
            provinceBox .setText("");
             phonenumberbox.setText("");
             labelPhoto.setIcon(new ImageIcon());

          
        } catch (Exception e) {
            e.printStackTrace();
        }
     
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(labelPhoto.getWidth(), labelPhoto.getHeight(), Image.SCALE_SMOOTH));
        labelPhoto.setIcon(imageicon);

        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[ ]buf = new byte[1024];
            for(int readNum;(readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            photo=bos.toByteArray();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnChooseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 idBox.setText("");
                  BirthdateBox.setDate(new Date());
                    FirstnameBox.setText("");
        LastnameBox.setText("");
    
   phonenumberbox.setText("");

   
     
       villageBox.setText("");
     cityBox.setText("");
     provinceBox.setText("");
     
     labelPhoto.setIcon(new ImageIcon());
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser BirthdateBox;
    private javax.swing.JTextField FirstnameBox;
    private javax.swing.JTextField LastnameBox;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cityBox;
    private javax.swing.JTextField idBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JTextField phonenumberbox;
    private javax.swing.JTextField provinceBox;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JTable tbModel;
    private javax.swing.JTextField villageBox;
    // End of variables declaration//GEN-END:variables
}
