
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import org.graalvm.compiler.nodes.NodeView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ko
 */
public class SendForm extends javax.swing.JFrame {

    /**
     * Creates new form SendForm
     */
    DefaultTableModel model  = new DefaultTableModel();
    public SendForm() {
        initComponents();
       model  = (DefaultTableModel)jTable1.getModel();
       showData();
    }
    
    int selectRow1;
      // Function To Resize The Image To Fit Into JLabel
     public ImageIcon ResizeImage(String ImagePath, byte[] pic)
    {
        ImageIcon MyImage = null;
        if(ImagePath != null)
        {
           MyImage = new ImageIcon(ImagePath);
        }else
        {
            MyImage = new ImageIcon(pic);
        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
     
      public void showData()
    {
        Connection c = MyConnection.getConnection();
        int rowCount = jTable1.getRowCount()-1;
        while(rowCount>=0)
        {
            model.removeRow(rowCount--);
        }
        try {
            String insert = "select * from tb_borrow where status = ? ";
            PreparedStatement ps = c.prepareStatement(insert);
            ps.setString(1, "ຍັງບໍ່ສົ່ງ");
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                String [] arr = {rs.getString("borrow_id").toString(),rs.getString("employee_id").toString(),rs.getString("member_id").toString(),rs.getString("book_id").toString(),rs.getDate("borrow_date").toString(),rs.getDate("send_date").toString(),rs.getString("status").toString()};
                model.addRow(arr);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idSearch = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        member_name = new javax.swing.JTextField();
        member_lastname = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        borrow_date = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/house.png"))); // NOI18N
        jButton3.setText("ໜ້າຫຼັກ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 110));

        jLabel3.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jLabel3.setText("ຄົ້ນຫາດ້ວຍລະຫັດການຢືມ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 160, 30));

        idSearch.setFont(new java.awt.Font("Saysettha OT", 1, 12)); // NOI18N
        jPanel1.add(idSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 150, 30));

        search.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/searchButton.png"))); // NOI18N
        search.setText("ຄົ້ນຫາ");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 110, 30));

        jLabel4.setFont(new java.awt.Font("Phetsarath OT", 3, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ຟອມການສົ່ງປຶ້ມ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 750, 60));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 110));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 452, 180, -1));

        jLabel5.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jLabel5.setText("ຊື່");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 20, 20));

        jLabel6.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jLabel6.setText("ນາມສະກຸນ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ລາຍລະອຽດການຢືມ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 20));

        jLabel8.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jLabel8.setText("ວັນທິ່ຢືມ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jLabel9.setText("ສະຖານະ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        member_name.setEditable(false);
        member_name.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jPanel2.add(member_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 150, -1));

        member_lastname.setEditable(false);
        member_lastname.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jPanel2.add(member_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 130, -1));

        jComboBox1.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ຍັງບໍ່ສົ່ງ", "ສົ່ງແລ້ວ", " " }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 110, -1));

        borrow_date.setEditable(false);
        borrow_date.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jPanel2.add(borrow_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 140, -1));

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/accpet2.png"))); // NOI18N
        jButton2.setText("ຕົກລົງ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 140, 40));

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Saysettha OT", 0, 14))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 160, 160));

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jTable1.setFont(new java.awt.Font("Phetsarath OT", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "brrow_id", "employee_id", "member_id", "book_id", "borrow_date", "Must_send_date", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int selectedRow = jTable1.getSelectedRow();
       selectRow1 = selectedRow;
       String select = "select m_name,m_lastname,m_picture from tb_member where m_id = ?";
        try {
             PreparedStatement ps = MyConnection.getConnection().prepareStatement(select);
             ps.setString(1, jTable1.getValueAt(selectedRow, 2).toString());
             ResultSet rs = ps.executeQuery();
             while(rs.next())
             {
                 member_name.setText(rs.getString("m_name").toString());
                 member_lastname.setText(rs.getString("m_lastname").toString());
                 jLabel10.setIcon(ResizeImage(null, rs.getBytes("m_picture")));
             }
             borrow_date.setText(jTable1.getValueAt(selectedRow, 4).toString());
             jComboBox1.setSelectedItem(jTable1.getValueAt(selectedRow, 6));
        } catch (Exception e) {
            e.printStackTrace();
        }
      
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String status = jComboBox1.getSelectedItem().toString();
        String update = "update tb_borrow set status = ? where borrow_id=?";
        try {
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(update);
            ps.setString(1, status);
             ps.setString(2, jTable1.getValueAt(selectRow1, 0).toString());
            if(ps.executeUpdate()==1)
            {
                JOptionPane.showMessageDialog(null, "Send book Sucessfully");
                showData();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        member_name.setText("");
         member_lastname.setText("");
          borrow_date.setText("");
          jComboBox1.setSelectedItem("Not_Send");
        jLabel10.setIcon(new ImageIcon());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
      String selct;
       int rowCount = jTable1.getRowCount()-1;
        while(rowCount>=0)
        {
            model.removeRow(rowCount--);
        }
      PreparedStatement ps ;
        try {
            if(idSearch.getText().equals(""))
            {
                 selct = "select * from tb_borrow where status=?";
                  ps  = MyConnection.getConnection().prepareStatement(selct);
                  ps.setString(1, "Not_Send");
             
            }
            else
            {
                 selct = "select * from tb_borrow where borrow_id=? and status = ?";
                   ps = MyConnection.getConnection().prepareStatement(selct);
                    ps.setString(1, idSearch.getText());
                   ps.setString(2, "Not_Send");
      
            }
            
            
      
             ResultSet rs= ps.executeQuery();
             while(rs.next())
             {
                 String [] arr = {rs.getString("borrow_id").toString(),rs.getString("employee_id").toString(),rs.getString("member_id").toString(),rs.getString("book_id").toString(),rs.getDate("borrow_date").toString(),rs.getDate("send_date").toString(),rs.getString("status").toString()};
                model.addRow(arr);
             }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_searchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField borrow_date;
    private javax.swing.JTextField idSearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField member_lastname;
    private javax.swing.JTextField member_name;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
